export const GAME_CONFIGS = {
  TX: {
    name: 'Texas',
    games: {
      'texas-two-step': {
        name: 'Texas Two Step',
        mainNumbers: { min: 1, max: 35, pick: 4 },
        bonusNumbers: { min: 1, max: 35, pick: 1 },
        hasBonus: true,
        poolRange: { min: 4, max: 25 },
        bonusCandidatesMax: 6,
        description: 'Pick 4 numbers from 1-35 + 1 bonus',
        tiers: [
          { id: '4of4b', label: '4/4 + Bonus', defaultChecked: true },
          { id: '4of4', label: '4/4', defaultChecked: true },
          { id: '3of4b', label: '3/4 + Bonus', defaultChecked: true },
          { id: '3of4', label: '3/4', defaultChecked: true },
          { id: '2of4b', label: '2/4 + Bonus', defaultChecked: false },
          { id: '2of4', label: '2/4', defaultChecked: false },
        ],
      },
      'lotto-texas': {
        name: 'Lotto Texas',
        mainNumbers: { min: 1, max: 54, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-54',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'cash-five': {
        name: 'Texas Cash Five',
        mainNumbers: { min: 1, max: 35, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-35',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      powerball: {
        name: 'Powerball',
        mainNumbers: { min: 1, max: 69, pick: 5 },
        bonusNumbers: { min: 1, max: 26, pick: 1 },
        hasBonus: true,
        poolRange: { min: 5, max: 35 },
        bonusCandidatesMax: 10,
        description: 'Pick 5 numbers from 1-69 + Powerball from 1-26',
        tiers: [
          { id: '5of5b', label: '5/5 + PB (Jackpot)', defaultChecked: true },
          { id: '5of5', label: '5/5', defaultChecked: true },
          { id: '4of5b', label: '4/5 + PB', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5b', label: '3/5 + PB', defaultChecked: false },
          { id: '3of5', label: '3/5', defaultChecked: false },
        ],
      },
      'mega-millions': {
        name: 'Mega Millions',
        mainNumbers: { min: 1, max: 70, pick: 5 },
        bonusNumbers: { min: 1, max: 25, pick: 1 },
        hasBonus: true,
        poolRange: { min: 5, max: 35 },
        bonusCandidatesMax: 10,
        description: 'Pick 5 numbers from 1-70 + Mega Ball from 1-25',
        tiers: [
          { id: '5of5b', label: '5/5 + MB (Jackpot)', defaultChecked: true },
          { id: '5of5', label: '5/5', defaultChecked: true },
          { id: '4of5b', label: '4/5 + MB', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5b', label: '3/5 + MB', defaultChecked: false },
          { id: '3of5', label: '3/5', defaultChecked: false },
        ],
      },
    },
  },
  CA: {
    name: 'California',
    games: {
      'superlotto-plus': {
        name: 'SuperLotto Plus',
        mainNumbers: { min: 1, max: 47, pick: 5 },
        bonusNumbers: { min: 1, max: 27, pick: 1 },
        hasBonus: true,
        poolRange: { min: 5, max: 30 },
        bonusCandidatesMax: 10,
        description: 'Pick 5 numbers from 1-47 + MEGA from 1-27',
        tiers: [
          { id: '5of5b', label: '5/5 + MEGA (Jackpot)', defaultChecked: true },
          { id: '5of5', label: '5/5', defaultChecked: true },
          { id: '4of5b', label: '4/5 + MEGA', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5b', label: '3/5 + MEGA', defaultChecked: false },
          { id: '3of5', label: '3/5', defaultChecked: false },
        ],
      },
      'fantasy-5-ca': {
        name: 'Fantasy 5',
        mainNumbers: { min: 1, max: 39, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-39',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
    },
  },
  NY: {
    name: 'New York',
    games: {
      'ny-lotto': {
        name: 'New York Lotto',
        mainNumbers: { min: 1, max: 59, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-59',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6b', label: '5/6 + Bonus', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'take-5-ny': {
        name: 'Take 5',
        mainNumbers: { min: 1, max: 39, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-39',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      cash4life: {
        name: 'Cash4Life',
        mainNumbers: { min: 1, max: 60, pick: 5 },
        bonusNumbers: { min: 1, max: 4, pick: 1 },
        hasBonus: true,
        poolRange: { min: 5, max: 30 },
        bonusCandidatesMax: 4,
        description: 'Pick 5 numbers from 1-60 + Cash Ball from 1-4',
        tiers: [
          { id: '5of5b', label: '5/5 + CB (Life)', defaultChecked: true },
          { id: '5of5', label: '5/5', defaultChecked: true },
          { id: '4of5b', label: '4/5 + CB', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5b', label: '3/5 + CB', defaultChecked: false },
          { id: '3of5', label: '3/5', defaultChecked: false },
        ],
      },
    },
  },
  FL: {
    name: 'Florida',
    games: {
      'florida-lotto': {
        name: 'Florida Lotto',
        mainNumbers: { min: 1, max: 53, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-53',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'fantasy-5-fl': {
        name: 'Fantasy 5',
        mainNumbers: { min: 1, max: 36, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-36',
        tiers: [
          { id: '5of5', label: '5/5 (Top Prize)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      'jackpot-triple-play': {
        name: 'Jackpot Triple Play',
        mainNumbers: { min: 1, max: 46, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-46',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
    },
  },
}
