export const POWERBALL_CONFIG = {
  name: 'Powerball',
  mainNumbers: { min: 1, max: 69, pick: 5 },
  bonusNumbers: { min: 1, max: 26, pick: 1 },
  hasBonus: true,
  poolRange: { min: 5, max: 35 },
  bonusCandidatesMax: 10,
  description: 'Pick 5 numbers from 1-69 + Powerball from 1-26',
  tiers: [
    { id: '5of5b', label: '5/5 + PB (Jackpot)', defaultChecked: true },
    { id: '5of5', label: '5/5', defaultChecked: true },
    { id: '4of5b', label: '4/5 + PB', defaultChecked: true },
    { id: '4of5', label: '4/5', defaultChecked: true },
    { id: '3of5b', label: '3/5 + PB', defaultChecked: false },
    { id: '3of5', label: '3/5', defaultChecked: false },
  ],
};

export const MEGA_MILLIONS_CONFIG = {
  name: 'Mega Millions',
  mainNumbers: { min: 1, max: 70, pick: 5 },
  bonusNumbers: { min: 1, max: 25, pick: 1 },
  hasBonus: true,
  poolRange: { min: 5, max: 35 },
  bonusCandidatesMax: 10,
  description: 'Pick 5 numbers from 1-70 + Mega Ball from 1-25',
  tiers: [
    { id: '5of5b', label: '5/5 + MB (Jackpot)', defaultChecked: true },
    { id: '5of5', label: '5/5', defaultChecked: true },
    { id: '4of5b', label: '4/5 + MB', defaultChecked: true },
    { id: '4of5', label: '4/5', defaultChecked: true },
    { id: '3of5b', label: '3/5 + MB', defaultChecked: false },
    { id: '3of5', label: '3/5', defaultChecked: false },
  ],
};

export const GAME_CONFIGS = {
  TX: {
    name: 'Texas',
    games: {
      'texas-two-step': {
        name: 'Texas Two Step',
        mainNumbers: { min: 1, max: 35, pick: 4 },
        bonusNumbers: { min: 1, max: 35, pick: 1 },
        hasBonus: true,
        poolRange: { min: 4, max: 25 },
        bonusCandidatesMax: 6,
        description: 'Pick 4 numbers from 1-35 + 1 bonus',
        tiers: [
          { id: '4of4b', label: '4/4 + Bonus', defaultChecked: true },
          { id: '4of4', label: '4/4', defaultChecked: true },
          { id: '3of4b', label: '3/4 + Bonus', defaultChecked: true },
          { id: '3of4', label: '3/4', defaultChecked: true },
          { id: '2of4b', label: '2/4 + Bonus', defaultChecked: false },
          { id: '2of4', label: '2/4', defaultChecked: false },
        ],
      },
      'lotto-texas': {
        name: 'Lotto Texas',
        mainNumbers: { min: 1, max: 54, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-54',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'cash-five': {
        name: 'Texas Cash Five',
        mainNumbers: { min: 1, max: 35, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-35',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  CA: {
    name: 'California',
    games: {
      'superlotto-plus': {
        name: 'SuperLotto Plus',
        mainNumbers: { min: 1, max: 47, pick: 5 },
        bonusNumbers: { min: 1, max: 27, pick: 1 },
        hasBonus: true,
        poolRange: { min: 5, max: 30 },
        bonusCandidatesMax: 10,
        description: 'Pick 5 numbers from 1-47 + MEGA from 1-27',
        tiers: [
          { id: '5of5b', label: '5/5 + MEGA (Jackpot)', defaultChecked: true },
          { id: '5of5', label: '5/5', defaultChecked: true },
          { id: '4of5b', label: '4/5 + MEGA', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5b', label: '3/5 + MEGA', defaultChecked: false },
          { id: '3of5', label: '3/5', defaultChecked: false },
        ],
      },
      'fantasy-5-ca': {
        name: 'Fantasy 5',
        mainNumbers: { min: 1, max: 39, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-39',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  NY: {
    name: 'New York',
    games: {
      'ny-lotto': {
        name: 'New York Lotto',
        mainNumbers: { min: 1, max: 59, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-59',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6b', label: '5/6 + Bonus', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'take-5-ny': {
        name: 'Take 5',
        mainNumbers: { min: 1, max: 39, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-39',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      cash4life: {
        name: 'Cash4Life',
        mainNumbers: { min: 1, max: 60, pick: 5 },
        bonusNumbers: { min: 1, max: 4, pick: 1 },
        hasBonus: true,
        poolRange: { min: 5, max: 30 },
        bonusCandidatesMax: 4,
        description: 'Pick 5 numbers from 1-60 + Cash Ball from 1-4',
        tiers: [
          { id: '5of5b', label: '5/5 + CB (Life)', defaultChecked: true },
          { id: '5of5', label: '5/5', defaultChecked: true },
          { id: '4of5b', label: '4/5 + CB', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5b', label: '3/5 + CB', defaultChecked: false },
          { id: '3of5', label: '3/5', defaultChecked: false },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  FL: {
    name: 'Florida',
    games: {
      'florida-lotto': {
        name: 'Florida Lotto',
        mainNumbers: { min: 1, max: 53, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-53',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'fantasy-5-fl': {
        name: 'Fantasy 5',
        mainNumbers: { min: 1, max: 36, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-36',
        tiers: [
          { id: '5of5', label: '5/5 (Top Prize)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      'jackpot-triple-play': {
        name: 'Jackpot Triple Play',
        mainNumbers: { min: 1, max: 46, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-46',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  PA: {
    name: 'Pennsylvania',
    games: {
      'match-6': {
        name: 'Match 6 Lotto',
        mainNumbers: { min: 1, max: 49, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-49',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'cash-5-pa': {
        name: 'Cash 5',
        mainNumbers: { min: 1, max: 43, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-43',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      'treasure-hunt': {
        name: 'Treasure Hunt',
        mainNumbers: { min: 1, max: 30, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 20 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-30',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  NJ: {
    name: 'New Jersey',
    games: {
      'pick-6-nj': {
        name: 'Pick-6',
        mainNumbers: { min: 1, max: 46, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-46',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'jersey-cash-5': {
        name: 'Jersey Cash 5',
        mainNumbers: { min: 1, max: 45, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-45',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  MA: {
    name: 'Massachusetts',
    games: {
      'megabucks-ma': {
        name: 'Megabucks',
        mainNumbers: { min: 1, max: 44, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-44',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'mass-cash': {
        name: 'Mass Cash',
        mainNumbers: { min: 1, max: 35, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-35',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  OH: {
    name: 'Ohio',
    games: {
      'classic-lotto-oh': {
        name: 'Classic Lotto',
        mainNumbers: { min: 1, max: 49, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-49',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'rolling-cash-5': {
        name: 'Rolling Cash 5',
        mainNumbers: { min: 1, max: 39, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-39',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  MD: {
    name: 'Maryland',
    games: {
      'multi-match': {
        name: 'Multi-Match',
        mainNumbers: { min: 1, max: 43, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-43',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'bonus-match-5': {
        name: 'Bonus Match 5',
        mainNumbers: { min: 1, max: 39, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-39',
        tiers: [
          { id: '5of5', label: '5/5 (Top Prize)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  GA: {
    name: 'Georgia',
    games: {
      'fantasy-5-ga': {
        name: 'Fantasy 5',
        mainNumbers: { min: 1, max: 42, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-42',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  NC: {
    name: 'North Carolina',
    games: {
      'cash-5-nc': {
        name: 'Cash 5',
        mainNumbers: { min: 1, max: 43, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-43',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  VA: {
    name: 'Virginia',
    games: {
      'bank-a-million': {
        name: 'Bank a Million',
        mainNumbers: { min: 1, max: 40, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-40',
        tiers: [
          { id: '6of6', label: '6/6 (Top Prize)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
        ],
      },
      'cash-5-va': {
        name: 'Cash 5',
        mainNumbers: { min: 1, max: 41, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-41',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  TN: {
    name: 'Tennessee',
    games: {
      'tennessee-cash': {
        name: 'Tennessee Cash',
        mainNumbers: { min: 1, max: 35, pick: 5 },
        bonusNumbers: { min: 1, max: 5, pick: 1 },
        hasBonus: true,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 5,
        description: 'Pick 5 numbers from 1-35 + Cash Ball from 1-5',
        tiers: [
          { id: '5of5b', label: '5/5 + CB (Jackpot)', defaultChecked: true },
          { id: '5of5', label: '5/5', defaultChecked: true },
          { id: '4of5b', label: '4/5 + CB', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5b', label: '3/5 + CB', defaultChecked: false },
          { id: '3of5', label: '3/5', defaultChecked: false },
        ],
      },
      'daily-tennessee-jackpot': {
        name: 'Daily Tennessee Jackpot',
        mainNumbers: { min: 1, max: 38, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-38',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  KY: {
    name: 'Kentucky',
    games: {
      'cash-ball-225': {
        name: 'Cash Ball 225',
        mainNumbers: { min: 1, max: 35, pick: 4 },
        bonusNumbers: { min: 1, max: 25, pick: 1 },
        hasBonus: true,
        poolRange: { min: 4, max: 20 },
        bonusCandidatesMax: 10,
        description: 'Pick 4 numbers from 1-35 + Cash Ball from 1-25',
        tiers: [
          { id: '4of4b', label: '4/4 + CB (Top Prize)', defaultChecked: true },
          { id: '4of4', label: '4/4', defaultChecked: true },
          { id: '3of4b', label: '3/4 + CB', defaultChecked: true },
          { id: '3of4', label: '3/4', defaultChecked: true },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  IL: {
    name: 'Illinois',
    games: {
      'illinois-lotto': {
        name: 'Lotto',
        mainNumbers: { min: 1, max: 50, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-50',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'lucky-day-lotto': {
        name: 'Lucky Day Lotto',
        mainNumbers: { min: 1, max: 45, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-45',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  MI: {
    name: 'Michigan',
    games: {
      'lotto-47': {
        name: 'Lotto 47',
        mainNumbers: { min: 1, max: 47, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-47',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'fantasy-5-mi': {
        name: 'Fantasy 5',
        mainNumbers: { min: 1, max: 39, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-39',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  IN: {
    name: 'Indiana',
    games: {
      'hoosier-lotto': {
        name: 'Hoosier Lotto',
        mainNumbers: { min: 1, max: 46, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-46',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'cash-5-in': {
        name: 'Cash 5',
        mainNumbers: { min: 1, max: 45, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-45',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  MO: {
    name: 'Missouri',
    games: {
      'mo-millions': {
        name: 'Lotto',
        mainNumbers: { min: 1, max: 42, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-42',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'show-me-cash': {
        name: 'Show Me Cash',
        mainNumbers: { min: 1, max: 39, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-39',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  WI: {
    name: 'Wisconsin',
    games: {
      'megabucks-wi': {
        name: 'Megabucks',
        mainNumbers: { min: 1, max: 49, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-49',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'badger-5': {
        name: 'Badger 5',
        mainNumbers: { min: 1, max: 31, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 20 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-31',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      'supercash': {
        name: 'SuperCash!',
        mainNumbers: { min: 1, max: 39, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-39',
        tiers: [
          { id: '6of6', label: '6/6 (Top Prize)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  MN: {
    name: 'Minnesota',
    games: {
      'gopher-5': {
        name: 'Gopher 5',
        mainNumbers: { min: 1, max: 47, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-47',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      'northstar-cash': {
        name: 'Northstar Cash',
        mainNumbers: { min: 1, max: 31, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 20 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-31',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  AZ: {
    name: 'Arizona',
    games: {
      'the-pick': {
        name: 'The Pick',
        mainNumbers: { min: 1, max: 44, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-44',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'fantasy-5-az': {
        name: 'Fantasy 5',
        mainNumbers: { min: 1, max: 41, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-41',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      'triple-twist': {
        name: 'Triple Twist',
        mainNumbers: { min: 1, max: 42, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-42',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  WA: {
    name: 'Washington',
    games: {
      'wa-lotto': {
        name: 'Lotto',
        mainNumbers: { min: 1, max: 49, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-49',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'match-4': {
        name: 'Match 4',
        mainNumbers: { min: 1, max: 24, pick: 4 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 4, max: 20 },
        bonusCandidatesMax: 0,
        description: 'Pick 4 numbers from 1-24',
        tiers: [
          { id: '4of4', label: '4/4 (Top Prize)', defaultChecked: true },
          { id: '3of4', label: '3/4', defaultChecked: true },
          { id: '2of4', label: '2/4', defaultChecked: false },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  OR: {
    name: 'Oregon',
    games: {
      'oregon-megabucks': {
        name: 'Megabucks',
        mainNumbers: { min: 1, max: 48, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-48',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
  CO: {
    name: 'Colorado',
    games: {
      'colorado-lotto-plus': {
        name: 'Colorado Lotto+',
        mainNumbers: { min: 1, max: 40, pick: 6 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 6, max: 30 },
        bonusCandidatesMax: 0,
        description: 'Pick 6 numbers from 1-40',
        tiers: [
          { id: '6of6', label: '6/6 (Jackpot)', defaultChecked: true },
          { id: '5of6', label: '5/6', defaultChecked: true },
          { id: '4of6', label: '4/6', defaultChecked: true },
          { id: '3of6', label: '3/6', defaultChecked: false },
        ],
      },
      'cash-5-co': {
        name: 'Cash 5',
        mainNumbers: { min: 1, max: 32, pick: 5 },
        bonusNumbers: null,
        hasBonus: false,
        poolRange: { min: 5, max: 25 },
        bonusCandidatesMax: 0,
        description: 'Pick 5 numbers from 1-32',
        tiers: [
          { id: '5of5', label: '5/5 (Jackpot)', defaultChecked: true },
          { id: '4of5', label: '4/5', defaultChecked: true },
          { id: '3of5', label: '3/5', defaultChecked: true },
          { id: '2of5', label: '2/5', defaultChecked: false },
        ],
      },
      powerball: POWERBALL_CONFIG,
      'mega-millions': MEGA_MILLIONS_CONFIG,
    },
  },
}
